SHOPDEMO/routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Frontend

Route::group(['prefix'=>'frontend','namespace'=>'Frontend', 'as'=>'frontend.'], function(){

    Route::get('/home','HomeController@index')->name('home');
    
    // BLOG
    Route::group(['prefix' => 'blog'], function(){
        Route::get('/index','BlogController@index')->name('blog');
        Route::get('/blog-single/{id}','BlogController@showBlogSingle')->name('blogSingle');
        Route::post('/blog-rate','BlogController@blogRate')->name('blogRate');
        Route::post('/blog-single/{id}','CommentsController@store')->name('cmtBlog');
    });

    // MEMBER
    Route::group(['prefix'=> 'member'], function(){
        Route::get('/login','MemberController@login')->name('login');
        Route::post('/login','MemberController@postLogin')->name('postLogin');
        Route::get('/logout','MemberController@logout')->name('logout');
        Route::get('/register','MemberController@register')->name('register');
        Route::post('/register','MemberController@postRegister')->name('postRegister');
        Route::get('/account','MemberController@show')->name('showAccount');
        Route::post('/account','MemberController@update')->name('updateAccount');
    });

    // PRODUCT
    Route::group(['prefix' => 'product'], function(){
        Route::get('/index','ProductController@show')->name('showProduct');
        Route::post('/search','ProductController@store')->name('searchProduct');
        Route::get('/price-range','ProductController@priceRange')->name('priceRange');
        Route::get('/index-shop','ProductController@showShop')->name('showShop');
    });

    // CART
    Route::group(['prefix' => 'cart'], function(){
        Route::get('/index','CartController@index')->name('cart');
        Route::post('/add-to-cart','CartController@store')->name('addToCart');
        Route::post('/cart-quanty-up','CartController@cartQtyUp')->name('cartQtyUp');
        Route::post('/cart-quanty-down','CartController@cartQtyDown')->name('cartQtyDown');
        Route::get('/delete-cart','CartController@destroy')->name('destroyCart');
    });

    // checkout
    Route::group(['prefix' => 'checkout'], function(){
        Route::get('/index','CheckoutController@index')->name('checkout');
        Route::get('/success','CheckoutController@show')->name('checkoutSuccess');
        Route::get('/send-mail','CheckoutController@store')->name('sendMail');
        Route::post('/save-user','CheckoutController@store')->name('saveHistory');
    });

    // check login 
    Route::group(['middleware' => 'member'], function () {
        Route::get('product/add','ProductController@create')->name('addProduct');
        Route::post('product/add','ProductController@createProduct')->name('createProduct');
        Route::get('product/edit/{id}','ProductController@update')->name('editProduct');
        Route::post('product/edit/{id}','ProductController@updateProduct')->name('updateProduct');
        Route::get('product/delete/{id}','ProductController@destroy')->name('deleteProduct');
        Route::get('product/details/{id}','ProductController@index')->name('detailProduct');
    });



    // Send-mail
    Route::get('/index','MailController@index')->name('indexMail');

    Route::get('/contact','ContactController@index')->name('contact');

    Route::get('/error','ErrorController@index')->name('error');

});

// Admin

Auth::routes();

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Auth'
], function () {
    Route::get('/', 'LoginController@showLoginForm');
    Route::get('/login', 'LoginController@showLoginForm');
    Route::post('/login', 'LoginController@login');
    Route::get('/logout', 'LoginController@logout');
});


Route::group([
    'prefix'=> 'admin', // tiền tố vào sau link
    'namespace'=>'Admin',
    'as'=>'admin.', 
    'middleware' => ['admin']
], function(){
//dashboard
    Route::get('/dashboard','DashboardController@index')->name('dashboard');

// user
    Route::get('/update','UserController@profile')->name('profile');
    Route::post('/update','UserController@update')->name('updateProfile');

// country
    Route::get('/country','CountryController@country')->name('country');
    Route::get('/add-country','CountryController@addCountry')->name('addCountry');
    Route::get('/delete-country/{id}','CountryController@deleteCountry')->name('deleteCountry');
    Route::post('/add-country','CountryController@createCountry')->name('createCountry');

// category
    Route::get('/category','CategoryController@show')->name('category');
    Route::get('/add-category','CategoryController@create')->name('addCategory');
    Route::get('/delete-category/{id}','CategoryController@destroy')->name('deleteCategory');
    Route::post('/add-category','CategoryController@createCategory')->name('createCategory');

// brand
    Route::get('/brand','BrandController@show')->name('brand');
    Route::get('/add-brand','BrandController@create')->name('addBrand');
    Route::post('/add-brand','BrandController@createBrand')->name('createBrand');
    Route::get('/delete-brand/{id}','BrandController@destroy')->name('deleteBrand');

// blog
    Route::get('/blog','BlogController@list')->name('blog');
    Route::get('/add-blog','BlogController@addBlog')->name('addBlog');
    Route::post('/add-blog','BlogController@createBlog')->name('createBlog');
    Route::get('/edit-blog/{id}','BlogController@editBlog')->name('editBlog');
    Route::post('/edit-blog/{id}','BlogController@updateBlog')->name('updateBlog');
    Route::get('/delete-blog/{id}','BlogController@deleteBlog')->name('deleteBlog');


    Route::get('/form-basic','FormBasicController@formBasic')->name('formBasic');
    Route::get('/table-basic','TableBasicController@tableBasic')->name('tableBasic');
    Route::get('/icon-material','IconMaterialController@iconMaterial')->name('iconMaterial');
    Route::get('/blank','StarterKitController@starterKit')->name('blank');
    Route::get('/error-404','Error404Controller@error404')->name('error404');
});

SHOPDEMO/app/Http/Controllers/Frontend/BlogController.php
<?php

namespace App\Http\Controllers\Frontend;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Blog;
use App\Models\Rate;
use App\Models\Comments;
use Illuminate\Support\Facades\Auth;
class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Blog::paginate(3);
        return view('frontend.blog.blog',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function showBlogSingle($id)
    {
        // dd($id);
        $blog = Blog::find($id);
         // get previous user id
        $previous = Blog::where('id', '<', $blog->id)->max('id');

        // get next user id
        $next = Blog::where('id', '>', $blog->id)->min('id');
        $comments = Comments::where('blog_id',$id)->get();
        $rating = Rate::where('blog_id',$id)->avg('point');
        $rating = round($rating);
        // dd($sumPoint);
        // tong so diem / so lan danh gia cua bai do , thi tron: round php
        // dd($comments);
        return view('frontend.blog.blogSingle',compact('blog', 'previous','next','comments','rating'));
    }

    //Rate
    public function blogRate()
    {
        $blog_id = $_POST['idBlog'];
        $point = $_POST['point'];
        $rate = Rate::create([
            'blog_id' => $blog_id,
            'user_id' =>Auth::user()->id,
            'point' => $point
        ]);
        return redirect()->route('frontend.blogSingle',['id'=>$blog_id]);
    }

    public function cmtBlogSingle(Request $request)
    {
        dd($request->all());
        
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

SHOPDEMO/app/Http/Controllers/Frontend/CartController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(session()->has('cart')){
            $carts = session()->get('cart');
            return view('frontend.cart.cart', compact('carts'));
        }
        return view('frontend.cart.cart');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // session()->forget('cart');
        $id = $_POST['idProduct'];
        $product = Product::find($id)->toArray();
        $cart = session()->get('cart');
        // dd($product);
        if(isset($cart[$id])){
            $cart[$id]['qty'] = $cart[$id]['qty'] += 1;
        }else {
            $cart[$id] = [
                'img' => current(json_decode($product['images'])),
                'price' => $product['price'],
                'name' => $product['name'],
                'qty' => 1
            ];
        }
        session()->put('cart', $cart);
        $countCart = count(session()->get('cart'));
        return response()->json([
            'code' => 200,
            'countCart' => $countCart,
            'message' => 'success'
        ],200);

        // echo "<pre>";
        // print_r(session()->get('cart'));
    }

    public function cartQtyUp()
    {
        // session()->forget('cart');
        $idProduct = $_POST['valID'];
        if(session()->has('cart'))
        {
            $cart = session()->get('cart');
            $total = 0;
            foreach($cart as $key => $value){
                if($key == $idProduct){
                    $cart[$key]['qty'] += 1;
                }
            }
            session()->put('cart',$cart);
            foreach($cart as $key => $value){
                $total += $value['price'] * $value['qty'];
            }
            return response()->json([
                'total' => $total
            ]);
        }else{
            echo "Session does not exist! ";
        }
    }

    public function cartQtyDown()
    {
        $idProduct = $_POST['valID'];
        if(session()->has('cart')){
            $cart = session()->get('cart');
            $total = 0;
            foreach ($cart as $key => $value) {
                if($key == $idProduct){
                    $cart[$key]['qty'] -= 1;
                }
                if($cart[$key]['qty'] < 1){
                    unset($cart[$key]);
                }
            }
            session()->put('cart', $cart);
            foreach($cart as $key => $value){
                $total -= $value['price'] * $value['qty'];
            }
            return response()->json([
                'total' => $total
            ]);
        }else{
            echo "Session does not exist! ";
        }
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy()
    {
        $idProduct = $_GET['valID'];
        if(session()->has('cart')){
            $cart = session()->get('cart');
            foreach ($cart as $key => $value) {
                if($key == $idProduct){
                    unset($cart[$key]);
                }
            }
            session()->put('cart', $cart);
        }else{
            echo "Session does not exist! ";
        }
    }
}

SHOPDEMO/app/Http/Controllers/Frontend/CheckoutController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\MemberRegisterRequest;
use Illuminate\Support\Facades\Auth;
use App\Models\User;
use App\Models\History;
use Mail;
use App\Services\Service;
class CheckoutController extends Controller
{
    protected $service;

    public function __construct(Service $service)
    {
        $this->service = $service;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('frontend.checkout.checkout');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $total = 0;
        if(session()->has('cart')){
            $carts = session()->get('cart');
            foreach ($carts as $key => $value) {
                $total += $value['price'] * $value['qty'];
            }
        }
        if(Auth::check()){
            $user = Auth::user();
            
            //send email for user
            $this->service->sendMailOrderComplete($user);

            //save history
            History::create([
                'email' => $user->email,
                'phone' => $user->phone,
                'name'  => $user->name,
                'id_user' => $user->id,
                'price' => "$".$total
            ]);
        }else{
            //register
            $this->service->postRegister($request->all());

            //send email
            $user = $request;
            $this->service->sendMailOrderComplete($user);

            // save history
            $user = User::latest()->limit(1)->get();
            foreach ($user as $key => $value) {
                History::create([
                'email' => $value->email,
                'phone' => $value->phone,
                'name'  => $value->name,
                'id_user' => $value->id,
                'price' => "$".$total
                ]);
            }
        }
        return view('frontend.checkout.success');
        // return view('frontend.sendemail.mail',compact('emailBody'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        return view('frontend.checkout.success');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

SHOPDEMO/app/Http/Controllers/Frontend/ErrorController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ErrorController extends Controller
{
    public function index(){
        return view('frontend.error.error');
    }
}

SHOPDEMO/resources/views/frontend/checkout/checkout.blade.php
@extends('frontend.layout.index-cart')
@section('title','Checkout')
@section('content')
<section id="cart_items">
    <div class="container">
        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li class="active">Check out</li>
            </ol>
        </div><!--/breadcrums-->
        @if(!auth()->check())
            <div class="row">
                <div class="col-sm-4"></div>
                <div class="col-sm-4">
                    <div class="signup-form"><!--sign up form-->
                        <h2>Please Register!</h2>
                        @if(session('success'))
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                                <h4><i class="icon fa fa-check"></i>Thong bao!</h4>
                                {{session('success')}}
                            </div>
                        @endif
                        @if($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form action="{{ route('frontend.saveHistory') }}" method ="post" enctype="multipart/form-data">
                            @csrf
                            <input type="text" name="name" placeholder="Name"/>
                            <input type="email" name="email" placeholder="Email Address"/>
                            <input type="number" name="phone" placeholder="Phone"/>
                            <input type="password" name="password" placeholder="Password"/>
                            <input type="password" name="password_confirmation" placeholder="Confirm Password"/>
                            <input style="padding-top: 10px;" type="file" name="avatar" id="avatar">
                            <button type="submit" class="btn btn-default">Signup</button>
                        </form>
                    </div><!--/sign up form-->
                </div>
                <div class="col-sm-4"></div>
            </div>
        @endif
        <div class="review-payment">
            <h2>Review & Payment</h2>
        </div>

        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Item</td>
                        <td class="description"></td>
                        <td class="price">Price</td>
                        <td class="quantity">Quantity</td>
                        <td class="total">Total</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @php 
                        $total = 0;
                    @endphp
                    @if(session()->has('cart'))
                        <?php 
                            $carts = session()->get('cart');
                        ?>
                        @foreach($carts as $key => $value)
                            @php 
                                $sum = $value['price'] * $value['qty'];
                                $total += $sum;
                            @endphp
                            <tr id="{{$key}}">
                                <td class="cart_product">
                                    @if(!auth()->check())
                                        <a href=""><img src="../../upload/product/16/{{ $value['img'] }}" alt=""></a>
                                    @else
                                        <a href=""><img src="../../upload/product/{{ Auth::user()->id}}/{{ $value['img'] }}" alt=""></a>
                                    @endif
                                </td>
                                <td class="cart_description">
                                    <h4><a href="">{{ $value['name'] }}</a></h4>
                                    <p>Web ID: 1089772</p>
                                </td>
                                <td class="cart_price">
                                    <p>${{ $value['price'] }}</p>
                                </td>
                                <td class="cart_quantity">
                                    <div class="cart_quantity_button">
                                        <a class="cart_quantity_up" href=""> + </a>
                                        <input class="cart_quantity_input" type="text" name="quantity" value="{{ $value['qty'] }}" autocomplete="off" size="2">
                                        <a class="cart_quantity_down" href=""> - </a>
                                    </div>
                                </td>
                                <td class="cart_total">
                                    <p class="cart_total_price">
                                    <?php 
                                        echo "$".$sum;
                                    ?></p>
                                </td>
                                <td class="cart_delete">
                                    <a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <p style="color:red;">Khong co san pham nao!</p>
                    @endif
                    <tr>
                        <td colspan="4">&nbsp;</td>
                        <td colspan="2">
                            <table class="table table-condensed total-result">
                                <tr>
                                    <td>Cart Sub Total</td>
                                    <td><span class="total"><?php echo "$".$total ?></span></td>
                                </tr>
                                <tr>
                                    <td>Exo Tax</td>
                                    <td>$0</td>
                                </tr>
                                <tr class="shipping-cost">
                                    <td>Shipping Cost</td>
                                    <td>Free</td>										
                                </tr>
                                <tr>
                                    <td>Total</td>
                                    <td><span><span class="total"><?php echo "$".$total ?></span></td>
                                </tr>
                                <tr class="btn-order" >
                                    <td>
                                        <a class="btn btn-primary btn_order" href=" {{ route('frontend.sendMail') }}">Place order now</a>  
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="payment-options">
                <span>
                    <label><input type="checkbox"> Direct Bank Transfer</label>
                </span>
                <span>
                    <label><input type="checkbox"> Check Payment</label>
                </span>
                <span>
                    <label><input type="checkbox"> Paypal</label>
                </span>
            </div>
    </div>
</section> <!--/#cart_items-->
@endsection

SHOPDEMO/resources/views/frontend/checkout/success.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title') | E-Shopper</title>
    <link href="{{asset('frontend/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('frontend/css/font-awesome.min.css')}}" rel="stylesheet">
    <link href="{{asset('frontend/css/prettyPhoto.css')}}" rel="stylesheet">
    <link href="{{asset('frontend/css/price-range.css')}}" rel="stylesheet">
    <link href="{{asset('frontend/css/animate.css')}}" rel="stylesheet">
	<link href="{{asset('frontend/css/main.css')}}" rel="stylesheet">
	<link href="{{asset('frontend/css/responsive.css')}}" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="{{asset('frontend/js/html5shiv.js')}}"></script>
    <script src="{{asset('frontend/js/respond.min.js')}}"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	<!-- header -->
    @include('frontend.layout.header')

    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="alert alert-dismissible" style="background: #FE980F; color: white;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                <h4><i class="icon fa fa-check"></i>Thong bao!</h4>
                <h1>Đặt hàng thành công!</h1>
                <h4>Vui lòng check mail để xem thông tin đơn hàng!</h4>
            </div>
        </div>
        <div class="col-sm-4"></div>
    </div>

    @include('frontend.layout.footer')

    <script src="{{asset('frontend/js/jquery.js')}}"></script>
	<script src="{{asset('frontend/js/bootstrap.min.js')}}"></script>
	<script src="{{asset('frontend/js/jquery.scrollUp.min.js')}}"></script>
	<script src="{{asset('frontend/js/price-range.js')}}"></script>
    <script src="{{asset('frontend/js/jquery.prettyPhoto.js')}}"></script>
    <script src="{{asset('frontend/js/main.js')}}"></script>
    <script type="text/javascript" src="{{asset('http://maps.google.com/maps/api/js?sensor=true')}}"></script>
    <script type="text/javascript" src="{{asset('frontend/js/gmaps.js')}}"></script>
	<script src="{{asset('frontend/js/contact.js')}}"></script>
	<script src="{{asset('frontend/js/price-range.js')}}"></script>
</body>
</html>