SHOPDEMO/routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Frontend

Route::group(['prefix'=>'frontend','namespace'=>'Frontend', 'as'=>'frontend.'], function(){

    Route::get('/home','HomeController@index')->name('home');
    
    // BLOG
    Route::group(['prefix' => 'blog'], function(){
        Route::get('/index','BlogController@index')->name('blog');
        Route::get('/blog-single/{id}','BlogController@showBlogSingle')->name('blogSingle');
        Route::post('/blog-rate','BlogController@blogRate')->name('blogRate');
        Route::post('/blog-single/{id}','CommentsController@store')->name('cmtBlog');
    });

    // MEMBER
    Route::group(['prefix'=> 'member'], function(){
        Route::get('/login','MemberController@login')->name('login');
        Route::post('/login','MemberController@postLogin')->name('postLogin');
        Route::get('/logout','MemberController@logout')->name('logout');
        Route::get('/register','MemberController@register')->name('register');
        Route::post('/register','MemberController@postRegister')->name('postRegister');
        Route::get('/account','MemberController@show')->name('showAccount');
        Route::post('/account','MemberController@update')->name('updateAccount');
    });

    // PRODUCT
    Route::group(['prefix' => 'product'], function(){
        Route::get('/index','ProductController@show')->name('showProduct');
        Route::post('/search','ProductController@store')->name('searchProduct');
        Route::get('/price-range','ProductController@priceRange')->name('priceRange');
        Route::get('/index-shop','ProductController@showShop')->name('showShop');
    });

    // CART
    Route::group(['prefix' => 'cart'], function(){
        Route::get('/index','CartController@index')->name('cart');
        Route::post('/add-to-cart','CartController@store')->name('addToCart');
        Route::post('/cart-quanty-up','CartController@cartQtyUp')->name('cartQtyUp');
        Route::post('/cart-quanty-down','CartController@cartQtyDown')->name('cartQtyDown');
        Route::get('/delete-cart','CartController@destroy')->name('destroyCart');
    });

    // checkout
    Route::group(['prefix' => 'checkout'], function(){
        Route::get('/index','CheckoutController@index')->name('checkout');
        Route::get('/success','CheckoutController@show')->name('checkoutSuccess');
        Route::get('/send-mail','CheckoutController@store')->name('sendMail');
        Route::post('/save-user','CheckoutController@store')->name('saveHistory');
    });

    // check login 
    Route::group(['middleware' => 'member'], function () {
        Route::get('product/add','ProductController@create')->name('addProduct');
        Route::post('product/add','ProductController@createProduct')->name('createProduct');
        Route::get('product/edit/{id}','ProductController@update')->name('editProduct');
        Route::post('product/edit/{id}','ProductController@updateProduct')->name('updateProduct');
        Route::get('product/delete/{id}','ProductController@destroy')->name('deleteProduct');
        Route::get('product/details/{id}','ProductController@index')->name('detailProduct');
    });



    // Send-mail
    Route::get('/index','MailController@index')->name('indexMail');

    Route::get('/contact','ContactController@index')->name('contact');

    Route::get('/error','ErrorController@index')->name('error');

});

// Admin

Auth::routes();

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Auth'
], function () {
    Route::get('/', 'LoginController@showLoginForm');
    Route::get('/login', 'LoginController@showLoginForm');
    Route::post('/login', 'LoginController@login');
    Route::get('/logout', 'LoginController@logout');
});


Route::group([
    'prefix'=> 'admin', // tiền tố vào sau link
    'namespace'=>'Admin',
    'as'=>'admin.', 
    'middleware' => ['admin']
], function(){
//dashboard
    Route::get('/dashboard','DashboardController@index')->name('dashboard');

// user
    Route::get('/update','UserController@profile')->name('profile');
    Route::post('/update','UserController@update')->name('updateProfile');

// country
    Route::get('/country','CountryController@country')->name('country');
    Route::get('/add-country','CountryController@addCountry')->name('addCountry');
    Route::get('/delete-country/{id}','CountryController@deleteCountry')->name('deleteCountry');
    Route::post('/add-country','CountryController@createCountry')->name('createCountry');

// category
    Route::get('/category','CategoryController@show')->name('category');
    Route::get('/add-category','CategoryController@create')->name('addCategory');
    Route::get('/delete-category/{id}','CategoryController@destroy')->name('deleteCategory');
    Route::post('/add-category','CategoryController@createCategory')->name('createCategory');

// brand
    Route::get('/brand','BrandController@show')->name('brand');
    Route::get('/add-brand','BrandController@create')->name('addBrand');
    Route::post('/add-brand','BrandController@createBrand')->name('createBrand');
    Route::get('/delete-brand/{id}','BrandController@destroy')->name('deleteBrand');

// blog
    Route::get('/blog','BlogController@list')->name('blog');
    Route::get('/add-blog','BlogController@addBlog')->name('addBlog');
    Route::post('/add-blog','BlogController@createBlog')->name('createBlog');
    Route::get('/edit-blog/{id}','BlogController@editBlog')->name('editBlog');
    Route::post('/edit-blog/{id}','BlogController@updateBlog')->name('updateBlog');
    Route::get('/delete-blog/{id}','BlogController@deleteBlog')->name('deleteBlog');


    Route::get('/form-basic','FormBasicController@formBasic')->name('formBasic');
    Route::get('/table-basic','TableBasicController@tableBasic')->name('tableBasic');
    Route::get('/icon-material','IconMaterialController@iconMaterial')->name('iconMaterial');
    Route::get('/blank','StarterKitController@starterKit')->name('blank');
    Route::get('/error-404','Error404Controller@error404')->name('error404');
});

SHOPDEMO/app/Http/Controllers/Frontend/BlogController.php
<?php

namespace App\Http\Controllers\Frontend;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Blog;
use App\Models\Rate;
use App\Models\Comments;
use Illuminate\Support\Facades\Auth;
class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Blog::paginate(3);
        return view('frontend.blog.blog',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function showBlogSingle($id)
    {
        // dd($id);
        $blog = Blog::find($id);
         // get previous user id
        $previous = Blog::where('id', '<', $blog->id)->max('id');

        // get next user id
        $next = Blog::where('id', '>', $blog->id)->min('id');
        $comments = Comments::where('blog_id',$id)->get();
        $rating = Rate::where('blog_id',$id)->avg('point');
        $rating = round($rating);
        // dd($sumPoint);
        // tong so diem / so lan danh gia cua bai do , thi tron: round php
        // dd($comments);
        return view('frontend.blog.blogSingle',compact('blog', 'previous','next','comments','rating'));
    }

    //Rate
    public function blogRate()
    {
        $blog_id = $_POST['idBlog'];
        $point = $_POST['point'];
        $rate = Rate::create([
            'blog_id' => $blog_id,
            'user_id' =>Auth::user()->id,
            'point' => $point
        ]);
        return redirect()->route('frontend.blogSingle',['id'=>$blog_id]);
    }

    public function cmtBlogSingle(Request $request)
    {
        dd($request->all());
        
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

SHOPDEMO/app/Http/Controllers/Frontend/CartController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(session()->has('cart')){
            $carts = session()->get('cart');
            return view('frontend.cart.cart', compact('carts'));
        }
        return view('frontend.cart.cart');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // session()->forget('cart');
        $id = $_POST['idProduct'];
        $product = Product::find($id)->toArray();
        $cart = session()->get('cart');
        // dd($product);
        if(isset($cart[$id])){
            $cart[$id]['qty'] = $cart[$id]['qty'] += 1;
        }else {
            $cart[$id] = [
                'img' => current(json_decode($product['images'])),
                'price' => $product['price'],
                'name' => $product['name'],
                'qty' => 1
            ];
        }
        session()->put('cart', $cart);
        $countCart = count(session()->get('cart'));
        return response()->json([
            'code' => 200,
            'countCart' => $countCart,
            'message' => 'success'
        ],200);

        // echo "<pre>";
        // print_r(session()->get('cart'));
    }

    public function cartQtyUp()
    {
        // session()->forget('cart');
        $idProduct = $_POST['valID'];
        if(session()->has('cart'))
        {
            $cart = session()->get('cart');
            $total = 0;
            foreach($cart as $key => $value){
                if($key == $idProduct){
                    $cart[$key]['qty'] += 1;
                }
            }
            session()->put('cart',$cart);
            foreach($cart as $key => $value){
                $total += $value['price'] * $value['qty'];
            }
            return response()->json([
                'total' => $total
            ]);
        }else{
            echo "Session does not exist! ";
        }
    }

    public function cartQtyDown()
    {
        $idProduct = $_POST['valID'];
        if(session()->has('cart')){
            $cart = session()->get('cart');
            $total = 0;
            foreach ($cart as $key => $value) {
                if($key == $idProduct){
                    $cart[$key]['qty'] -= 1;
                }
                if($cart[$key]['qty'] < 1){
                    unset($cart[$key]);
                }
            }
            session()->put('cart', $cart);
            foreach($cart as $key => $value){
                $total -= $value['price'] * $value['qty'];
            }
            return response()->json([
                'total' => $total
            ]);
        }else{
            echo "Session does not exist! ";
        }
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy()
    {
        $idProduct = $_GET['valID'];
        if(session()->has('cart')){
            $cart = session()->get('cart');
            foreach ($cart as $key => $value) {
                if($key == $idProduct){
                    unset($cart[$key]);
                }
            }
            session()->put('cart', $cart);
        }else{
            echo "Session does not exist! ";
        }
    }
}

SHOPDEMO/app/Http/Controllers/Frontend/CheckoutController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\MemberRegisterRequest;
use Illuminate\Support\Facades\Auth;
use App\Models\User;
use App\Models\History;
use Mail;
use App\Services\Service;
class CheckoutController extends Controller
{
    protected $service;

    public function __construct(Service $service)
    {
        $this->service = $service;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('frontend.checkout.checkout');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $total = 0;
        if(session()->has('cart')){
            $carts = session()->get('cart');
            foreach ($carts as $key => $value) {
                $total += $value['price'] * $value['qty'];
            }
        }
        if(Auth::check()){
            $user = Auth::user();
            
            //send email for user
            $this->service->sendMailOrderComplete($user);

            //save history
            History::create([
                'email' => $user->email,
                'phone' => $user->phone,
                'name'  => $user->name,
                'id_user' => $user->id,
                'price' => "$".$total
            ]);
        }else{
            //register
            $this->service->postRegister($request->all());

            //send email
            $user = $request;
            $this->service->sendMailOrderComplete($user);

            // save history
            $user = User::latest()->limit(1)->get();
            foreach ($user as $key => $value) {
                History::create([
                'email' => $value->email,
                'phone' => $value->phone,
                'name'  => $value->name,
                'id_user' => $value->id,
                'price' => "$".$total
                ]);
            }
        }
        return view('frontend.checkout.success');
        // return view('frontend.sendemail.mail',compact('emailBody'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        return view('frontend.checkout.success');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

SHOPDEMO/app/Http/Controllers/Frontend/ErrorController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ErrorController extends Controller
{
    public function index(){
        return view('frontend.error.error');
    }
}

SHOPDEMO/resources/views/frontend/shop/products.blade.php
@foreach($products as $product)
<div class="col-sm-4">
    <div class="product-image-wrapper">
        <div class="single-products">
                <div class="productinfo text-center">
                    @if(!auth()->check())
                        <img src="../../upload/product/16/{{ current(json_decode($product['images'])) }}" alt="" />
                    @else
                        <img src="../../upload/product/{{ Auth::user()->id}}/{{ current(json_decode($product['images'])) }}" alt="" />
                    @endif
                    <h2>${{ $product['price'] }}</h2>
                    <p>{{ $product['name'] }}</p>
                    <a id="{{ $product['id'] }}" href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
                <div class="product-overlay">
                    <div class="overlay-content">
                        <h2>{{ $product['price'] }}</h2>
                        <p>{{ $product['name'] }}</p>
                        <a id="{{ $product['id'] }}"  href="" class="btn btn-default add-to-cart btn_addToCart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                        <a href="{{route('frontend.detailProduct',['id'=>$product['id']])}}" class="btn btn-default add-to-cart">Detail</a>
                    </div>
                </div>
        </div>
        <div class="choose">
            <ul class="nav nav-pills nav-justified">
                <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
            </ul>
        </div>
    </div>
</div>
@endforeach
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $('.btn_addToCart').click(function(){
            var idProduct = $(this).attr('id');
            // alert(idProduct);
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                type: "POST",
                dataType: 'json',
                url: "{{ route('frontend.addToCart') }}",
                data:{
                    idProduct:idProduct
                },
                success:function(data){
                        $('span.countCart').text(data.countCart);
                        if(data.code == 200){
                            alert('Add to cart success!')
                        }
                }
            });
            return false;
        })
    })
</script>

SHOPDEMO/resources/views/frontend/shop/shop.blade.php
@extends('frontend.layout.index')
@section('title','Shop')
@section('content')
<style>
    select{
        width: 166px;
        height: 33px;
    }
    .nameProduct {
        margin-left: 15px;
        width: 155px;
        border: none;
        background: #F0F0E9;
        height: 33px;
        padding-left: 10px;
    }
</style>
<div class="features_items"><!--features_items-->
    <h2 class="title text-center">Features Items</h2>
    <div class="form_search ">
        <form action="{{ route('frontend.searchProduct')}}">
            @csrf
            <input class="nameProduct" type="text" name="nameProduct" placeholder="Name product"/>
            <select class="price" name="price" id="price">
                <option value="" selected>Choose price</option>
                <option value="50-500">$50-$500</option>
                <option value="500-1000">$500-$1000</option>
                <option value="1000-5000">$1000-$5000</option>
            </select>
            <select id="category" name="category">
                <option value="" selected>Choose category</option>
                    @foreach($categorys as $category)
                            <option value="{{$category['id']}}"
                            >{{$category['name']}}
                            </option>
                    @endforeach
            </select>
            <select id="brand" name="brand">
                <option value="" selected>Choose brand</option>
                    @foreach($brands as $brand)
                            <option value="{{$brand['id']}}"
                            >{{$brand['name']}}
                            </option>
                    @endforeach
            </select>
            <select class="status" id="status" name="status">
                <option value="" selected>Status</option>
                <option value="0">New</option>
                <option value="1">Sale</option>
            </select>
            <button id="btn_search" style="border: none;background: #FE980F;height: 33px;color: #ffffff;margin-left: 15px;margin-top: 10px;margin-bottom: 10px;width: 90px;">Search</button>
        </form>
    </div>
    <div id="updateDiv">
        @foreach($products as $product)
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                        <div class="productinfo text-center">
                            @if(!auth()->check())
                                <img src="../../upload/product/16/{{ current(json_decode($product['images'])) }}" alt="" />
                            @else
                                <img src="../../upload/product/{{ Auth::user()->id}}/{{ current(json_decode($product['images'])) }}" alt="" />
                            @endif
                            <h2>${{ $product['price'] }}</h2>
                            <p>{{ $product['name'] }}</p>
                            <a id="{{ $product['id'] }}" href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                        </div>
                        <div class="product-overlay">
                            <div class="overlay-content">
                                <h2>{{ $product['price'] }}</h2>
                                <p>{{ $product['name'] }}</p>
                                <a id="{{ $product['id'] }}"  href="" class="btn btn-default add-to-cart btn_addToCart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                <a href="{{route('frontend.detailProduct',['id'=>$product['id']])}}" class="btn btn-default add-to-cart">Detail</a>
                            </div>
                        </div>
                </div>
                <div class="choose">
                    <ul class="nav nav-pills nav-justified">
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                    </ul>
                </div>
            </div>
        </div>
        @endforeach
    </div>
    
</div>
<ul class="pagination">
    {{ $products->links() }}
</ul>
<script>
    $(document).ready(function(){
        $('#btn_search').click(function(){
            var nameProduct = $(this).closest('div.form_search').find('input.nameProduct').val();
            var price = $(this).closest('div.form_search').find('select#price').val();
            var category = $(this).closest('div.form_search').find('select#category').val();
            var brand = $(this).closest('div.form_search').find('select#brand').val();
            var status = $(this).closest('div.form_search').find('select#status').val();
            // console.log(price)
            $.ajaxSetup({
					headers: {
						'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
					    }
				    });
            $.ajax({
                type: "post",
                url: "{{ route('frontend.searchProduct') }}",
                data: {nameProduct:nameProduct,price:price,category:category,brand:brand,status:status},
                success:function(data){
                    $('#updateDiv').html(data);
                }
            })
            return false;
        });
    })
</script>
@endsection

@section('slider')
<section id="advertisement">
    <div class="container">
        <img src="../images/shop/advertisement.jpg" alt="" />
    </div>
</section>
@endsection